// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.1
// source: proto/plexv1/plex.proto

package plexv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlexBridgeService_Status_FullMethodName           = "/muxcore.playback.plex.v1.PlexBridgeService/Status"
	PlexBridgeService_TerminateSession_FullMethodName = "/muxcore.playback.plex.v1.PlexBridgeService/TerminateSession"
	PlexBridgeService_ListSyncLists_FullMethodName    = "/muxcore.playback.plex.v1.PlexBridgeService/ListSyncLists"
	PlexBridgeService_ListSessions_FullMethodName     = "/muxcore.playback.plex.v1.PlexBridgeService/ListSessions"
	PlexBridgeService_PlayURL_FullMethodName          = "/muxcore.playback.plex.v1.PlexBridgeService/PlayURL"
)

// PlexBridgeServiceClient is the client API for PlexBridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlexBridgeServiceClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*TerminateSessionResponse, error)
	ListSyncLists(ctx context.Context, in *ListSyncListsRequest, opts ...grpc.CallOption) (*ListSyncListsResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	PlayURL(ctx context.Context, in *PlayURLRequest, opts ...grpc.CallOption) (*PlayURLResponse, error)
}

type plexBridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlexBridgeServiceClient(cc grpc.ClientConnInterface) PlexBridgeServiceClient {
	return &plexBridgeServiceClient{cc}
}

func (c *plexBridgeServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, PlexBridgeService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plexBridgeServiceClient) TerminateSession(ctx context.Context, in *TerminateSessionRequest, opts ...grpc.CallOption) (*TerminateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateSessionResponse)
	err := c.cc.Invoke(ctx, PlexBridgeService_TerminateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plexBridgeServiceClient) ListSyncLists(ctx context.Context, in *ListSyncListsRequest, opts ...grpc.CallOption) (*ListSyncListsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSyncListsResponse)
	err := c.cc.Invoke(ctx, PlexBridgeService_ListSyncLists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plexBridgeServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, PlexBridgeService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plexBridgeServiceClient) PlayURL(ctx context.Context, in *PlayURLRequest, opts ...grpc.CallOption) (*PlayURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayURLResponse)
	err := c.cc.Invoke(ctx, PlexBridgeService_PlayURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlexBridgeServiceServer is the server API for PlexBridgeService service.
// All implementations must embed UnimplementedPlexBridgeServiceServer
// for forward compatibility.
type PlexBridgeServiceServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	TerminateSession(context.Context, *TerminateSessionRequest) (*TerminateSessionResponse, error)
	ListSyncLists(context.Context, *ListSyncListsRequest) (*ListSyncListsResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	PlayURL(context.Context, *PlayURLRequest) (*PlayURLResponse, error)
	mustEmbedUnimplementedPlexBridgeServiceServer()
}

// UnimplementedPlexBridgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlexBridgeServiceServer struct{}

func (UnimplementedPlexBridgeServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedPlexBridgeServiceServer) TerminateSession(context.Context, *TerminateSessionRequest) (*TerminateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateSession not implemented")
}
func (UnimplementedPlexBridgeServiceServer) ListSyncLists(context.Context, *ListSyncListsRequest) (*ListSyncListsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSyncLists not implemented")
}
func (UnimplementedPlexBridgeServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedPlexBridgeServiceServer) PlayURL(context.Context, *PlayURLRequest) (*PlayURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlayURL not implemented")
}
func (UnimplementedPlexBridgeServiceServer) mustEmbedUnimplementedPlexBridgeServiceServer() {}
func (UnimplementedPlexBridgeServiceServer) testEmbeddedByValue()                           {}

// UnsafePlexBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlexBridgeServiceServer will
// result in compilation errors.
type UnsafePlexBridgeServiceServer interface {
	mustEmbedUnimplementedPlexBridgeServiceServer()
}

func RegisterPlexBridgeServiceServer(s grpc.ServiceRegistrar, srv PlexBridgeServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlexBridgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlexBridgeService_ServiceDesc, srv)
}

func _PlexBridgeService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlexBridgeServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlexBridgeService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlexBridgeServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlexBridgeService_TerminateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlexBridgeServiceServer).TerminateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlexBridgeService_TerminateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlexBridgeServiceServer).TerminateSession(ctx, req.(*TerminateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlexBridgeService_ListSyncLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSyncListsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlexBridgeServiceServer).ListSyncLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlexBridgeService_ListSyncLists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlexBridgeServiceServer).ListSyncLists(ctx, req.(*ListSyncListsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlexBridgeService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlexBridgeServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlexBridgeService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlexBridgeServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlexBridgeService_PlayURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlexBridgeServiceServer).PlayURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlexBridgeService_PlayURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlexBridgeServiceServer).PlayURL(ctx, req.(*PlayURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlexBridgeService_ServiceDesc is the grpc.ServiceDesc for PlexBridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlexBridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.playback.plex.v1.PlexBridgeService",
	HandlerType: (*PlexBridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _PlexBridgeService_Status_Handler,
		},
		{
			MethodName: "TerminateSession",
			Handler:    _PlexBridgeService_TerminateSession_Handler,
		},
		{
			MethodName: "ListSyncLists",
			Handler:    _PlexBridgeService_ListSyncLists_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _PlexBridgeService_ListSessions_Handler,
		},
		{
			MethodName: "PlayURL",
			Handler:    _PlexBridgeService_PlayURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plexv1/plex.proto",
}
