// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: proto/plexv1/plex.proto

package plexv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_plexv1_plex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plexv1_plex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_plexv1_plex_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Configured     bool                   `protobuf:"varint,1,opt,name=configured,proto3" json:"configured,omitempty"`
	BaseUrl        string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,3,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	SseConnected   bool                   `protobuf:"varint,4,opt,name=sse_connected,json=sseConnected,proto3" json:"sse_connected,omitempty"`
	MachineId      string                 `protobuf:"bytes,5,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_plexv1_plex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plexv1_plex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_plexv1_plex_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

func (x *StatusResponse) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *StatusResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *StatusResponse) GetSseConnected() bool {
	if x != nil {
		return x.SseConnected
	}
	return false
}

func (x *StatusResponse) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type TerminateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionRequest) Reset() {
	*x = TerminateSessionRequest{}
	mi := &file_proto_plexv1_plex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionRequest) ProtoMessage() {}

func (x *TerminateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plexv1_plex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionRequest.ProtoReflect.Descriptor instead.
func (*TerminateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_plexv1_plex_proto_rawDescGZIP(), []int{2}
}

func (x *TerminateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TerminateSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TerminateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateSessionResponse) Reset() {
	*x = TerminateSessionResponse{}
	mi := &file_proto_plexv1_plex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSessionResponse) ProtoMessage() {}

func (x *TerminateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plexv1_plex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateSessionResponse.ProtoReflect.Descriptor instead.
func (*TerminateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_plexv1_plex_proto_rawDescGZIP(), []int{3}
}

func (x *TerminateSessionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TerminateSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ListSyncListsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Refresh       bool                   `protobuf:"varint,3,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSyncListsRequest) Reset() {
	*x = ListSyncListsRequest{}
	mi := &file_proto_plexv1_plex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncListsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncListsRequest) ProtoMessage() {}

func (x *ListSyncListsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plexv1_plex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncListsRequest.ProtoReflect.Descriptor instead.
func (*ListSyncListsRequest) Descriptor() ([]byte, []int) {
	return file_proto_plexv1_plex_proto_rawDescGZIP(), []int{4}
}

func (x *ListSyncListsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListSyncListsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ListSyncListsRequest) GetRefresh() bool {
	if x != nil {
		return x.Refresh
	}
	return false
}

type PlexSyncItemMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	RootTitle            string                 `protobuf:"bytes,3,opt,name=root_title,json=rootTitle,proto3" json:"root_title,omitempty"`
	MetadataType         string                 `protobuf:"bytes,4,opt,name=metadata_type,json=metadataType,proto3" json:"metadata_type,omitempty"`
	ContentType          string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	MediaType            string                 `protobuf:"bytes,6,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	RatingKey            string                 `protobuf:"bytes,7,opt,name=rating_key,json=ratingKey,proto3" json:"rating_key,omitempty"`
	State                string                 `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	Failure              string                 `protobuf:"bytes,9,opt,name=failure,proto3" json:"failure,omitempty"`
	ItemsCount           int32                  `protobuf:"varint,10,opt,name=items_count,json=itemsCount,proto3" json:"items_count,omitempty"`
	ItemsCompleteCount   int32                  `protobuf:"varint,11,opt,name=items_complete_count,json=itemsCompleteCount,proto3" json:"items_complete_count,omitempty"`
	ItemsDownloadedCount int32                  `protobuf:"varint,12,opt,name=items_downloaded_count,json=itemsDownloadedCount,proto3" json:"items_downloaded_count,omitempty"`
	TotalSizeBytes       int64                  `protobuf:"varint,13,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	VideoResolution      string                 `protobuf:"bytes,14,opt,name=video_resolution,json=videoResolution,proto3" json:"video_resolution,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PlexSyncItemMessage) Reset() {
	*x = PlexSyncItemMessage{}
	mi := &file_proto_plexv1_plex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlexSyncItemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlexSyncItemMessage) ProtoMessage() {}

func (x *PlexSyncItemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plexv1_plex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlexSyncItemMessage.ProtoReflect.Descriptor instead.
func (*PlexSyncItemMessage) Descriptor() ([]byte, []int) {
	return file_proto_plexv1_plex_proto_rawDescGZIP(), []int{5}
}

func (x *PlexSyncItemMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlexSyncItemMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PlexSyncItemMessage) GetRootTitle() string {
	if x != nil {
		return x.RootTitle
	}
	return ""
}

func (x *PlexSyncItemMessage) GetMetadataType() string {
	if x != nil {
		return x.MetadataType
	}
	return ""
}

func (x *PlexSyncItemMessage) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *PlexSyncItemMessage) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *PlexSyncItemMessage) GetRatingKey() string {
	if x != nil {
		return x.RatingKey
	}
	return ""
}

func (x *PlexSyncItemMessage) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PlexSyncItemMessage) GetFailure() string {
	if x != nil {
		return x.Failure
	}
	return ""
}

func (x *PlexSyncItemMessage) GetItemsCount() int32 {
	if x != nil {
		return x.ItemsCount
	}
	return 0
}

func (x *PlexSyncItemMessage) GetItemsCompleteCount() int32 {
	if x != nil {
		return x.ItemsCompleteCount
	}
	return 0
}

func (x *PlexSyncItemMessage) GetItemsDownloadedCount() int32 {
	if x != nil {
		return x.ItemsDownloadedCount
	}
	return 0
}

func (x *PlexSyncItemMessage) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *PlexSyncItemMessage) GetVideoResolution() string {
	if x != nil {
		return x.VideoResolution
	}
	return ""
}

type PlexSyncListMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientIdentifier string                 `protobuf:"bytes,2,opt,name=client_identifier,json=clientIdentifier,proto3" json:"client_identifier,omitempty"`
	DeviceUserId     string                 `protobuf:"bytes,3,opt,name=device_user_id,json=deviceUserId,proto3" json:"device_user_id,omitempty"`
	DeviceName       string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DevicePlatform   string                 `protobuf:"bytes,5,opt,name=device_platform,json=devicePlatform,proto3" json:"device_platform,omitempty"`
	DeviceProduct    string                 `protobuf:"bytes,6,opt,name=device_product,json=deviceProduct,proto3" json:"device_product,omitempty"`
	Items            []*PlexSyncItemMessage `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlexSyncListMessage) Reset() {
	*x = PlexSyncListMessage{}
	mi := &file_proto_plexv1_plex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlexSyncListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlexSyncListMessage) ProtoMessage() {}

func (x *PlexSyncListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plexv1_plex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlexSyncListMessage.ProtoReflect.Descriptor instead.
func (*PlexSyncListMessage) Descriptor() ([]byte, []int) {
	return file_proto_plexv1_plex_proto_rawDescGZIP(), []int{6}
}

func (x *PlexSyncListMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlexSyncListMessage) GetClientIdentifier() string {
	if x != nil {
		return x.ClientIdentifier
	}
	return ""
}

func (x *PlexSyncListMessage) GetDeviceUserId() string {
	if x != nil {
		return x.DeviceUserId
	}
	return ""
}

func (x *PlexSyncListMessage) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *PlexSyncListMessage) GetDevicePlatform() string {
	if x != nil {
		return x.DevicePlatform
	}
	return ""
}

func (x *PlexSyncListMessage) GetDeviceProduct() string {
	if x != nil {
		return x.DeviceProduct
	}
	return ""
}

func (x *PlexSyncListMessage) GetItems() []*PlexSyncItemMessage {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListSyncListsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MachineIdentifier string                 `protobuf:"bytes,1,opt,name=machine_identifier,json=machineIdentifier,proto3" json:"machine_identifier,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Lists             []*PlexSyncListMessage `protobuf:"bytes,3,rep,name=lists,proto3" json:"lists,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListSyncListsResponse) Reset() {
	*x = ListSyncListsResponse{}
	mi := &file_proto_plexv1_plex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSyncListsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSyncListsResponse) ProtoMessage() {}

func (x *ListSyncListsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plexv1_plex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSyncListsResponse.ProtoReflect.Descriptor instead.
func (*ListSyncListsResponse) Descriptor() ([]byte, []int) {
	return file_proto_plexv1_plex_proto_rawDescGZIP(), []int{7}
}

func (x *ListSyncListsResponse) GetMachineIdentifier() string {
	if x != nil {
		return x.MachineIdentifier
	}
	return ""
}

func (x *ListSyncListsResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ListSyncListsResponse) GetLists() []*PlexSyncListMessage {
	if x != nil {
		return x.Lists
	}
	return nil
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_proto_plexv1_plex_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plexv1_plex_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_plexv1_plex_proto_rawDescGZIP(), []int{8}
}

type PlexSessionMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName        string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	ItemId          string                 `protobuf:"bytes,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Title           string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	PositionSeconds int64                  `protobuf:"varint,6,opt,name=position_seconds,json=positionSeconds,proto3" json:"position_seconds,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,7,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	Paused          bool                   `protobuf:"varint,8,opt,name=paused,proto3" json:"paused,omitempty"`
	Device          string                 `protobuf:"bytes,9,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlexSessionMessage) Reset() {
	*x = PlexSessionMessage{}
	mi := &file_proto_plexv1_plex_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlexSessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlexSessionMessage) ProtoMessage() {}

func (x *PlexSessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plexv1_plex_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlexSessionMessage.ProtoReflect.Descriptor instead.
func (*PlexSessionMessage) Descriptor() ([]byte, []int) {
	return file_proto_plexv1_plex_proto_rawDescGZIP(), []int{9}
}

func (x *PlexSessionMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PlexSessionMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlexSessionMessage) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *PlexSessionMessage) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *PlexSessionMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PlexSessionMessage) GetPositionSeconds() int64 {
	if x != nil {
		return x.PositionSeconds
	}
	return 0
}

func (x *PlexSessionMessage) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *PlexSessionMessage) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *PlexSessionMessage) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*PlexSessionMessage  `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_proto_plexv1_plex_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plexv1_plex_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_plexv1_plex_proto_rawDescGZIP(), []int{10}
}

func (x *ListSessionsResponse) GetSessions() []*PlexSessionMessage {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type PlayURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RatingKey     string                 `protobuf:"bytes,1,opt,name=rating_key,json=ratingKey,proto3" json:"rating_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayURLRequest) Reset() {
	*x = PlayURLRequest{}
	mi := &file_proto_plexv1_plex_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayURLRequest) ProtoMessage() {}

func (x *PlayURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plexv1_plex_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayURLRequest.ProtoReflect.Descriptor instead.
func (*PlayURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_plexv1_plex_proto_rawDescGZIP(), []int{11}
}

func (x *PlayURLRequest) GetRatingKey() string {
	if x != nil {
		return x.RatingKey
	}
	return ""
}

type PlayURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayURLResponse) Reset() {
	*x = PlayURLResponse{}
	mi := &file_proto_plexv1_plex_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayURLResponse) ProtoMessage() {}

func (x *PlayURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plexv1_plex_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayURLResponse.ProtoReflect.Descriptor instead.
func (*PlayURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_plexv1_plex_proto_rawDescGZIP(), []int{12}
}

func (x *PlayURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_plexv1_plex_proto protoreflect.FileDescriptor

const file_proto_plexv1_plex_proto_rawDesc = "" +
	"\n" +
	"\x17proto/plexv1/plex.proto\x12\x18muxcore.playback.plex.v1\"\x0f\n" +
	"\rStatusRequest\"\xb8\x01\n" +
	"\x0eStatusResponse\x12\x1e\n" +
	"\n" +
	"configured\x18\x01 \x01(\bR\n" +
	"configured\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12'\n" +
	"\x0factive_sessions\x18\x03 \x01(\x05R\x0eactiveSessions\x12#\n" +
	"\rsse_connected\x18\x04 \x01(\bR\fsseConnected\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x05 \x01(\tR\tmachineId\"P\n" +
	"\x17TerminateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"@\n" +
	"\x18TerminateSessionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"f\n" +
	"\x14ListSyncListsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x18\n" +
	"\arefresh\x18\x03 \x01(\bR\arefresh\"\xee\x03\n" +
	"\x13PlexSyncItemMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"root_title\x18\x03 \x01(\tR\trootTitle\x12#\n" +
	"\rmetadata_type\x18\x04 \x01(\tR\fmetadataType\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"media_type\x18\x06 \x01(\tR\tmediaType\x12\x1d\n" +
	"\n" +
	"rating_key\x18\a \x01(\tR\tratingKey\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\x12\x18\n" +
	"\afailure\x18\t \x01(\tR\afailure\x12\x1f\n" +
	"\vitems_count\x18\n" +
	" \x01(\x05R\n" +
	"itemsCount\x120\n" +
	"\x14items_complete_count\x18\v \x01(\x05R\x12itemsCompleteCount\x124\n" +
	"\x16items_downloaded_count\x18\f \x01(\x05R\x14itemsDownloadedCount\x12(\n" +
	"\x10total_size_bytes\x18\r \x01(\x03R\x0etotalSizeBytes\x12)\n" +
	"\x10video_resolution\x18\x0e \x01(\tR\x0fvideoResolution\"\xae\x02\n" +
	"\x13PlexSyncListMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11client_identifier\x18\x02 \x01(\tR\x10clientIdentifier\x12$\n" +
	"\x0edevice_user_id\x18\x03 \x01(\tR\fdeviceUserId\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12'\n" +
	"\x0fdevice_platform\x18\x05 \x01(\tR\x0edevicePlatform\x12%\n" +
	"\x0edevice_product\x18\x06 \x01(\tR\rdeviceProduct\x12C\n" +
	"\x05items\x18\a \x03(\v2-.muxcore.playback.plex.v1.PlexSyncItemMessageR\x05items\"\xaa\x01\n" +
	"\x15ListSyncListsResponse\x12-\n" +
	"\x12machine_identifier\x18\x01 \x01(\tR\x11machineIdentifier\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\tR\tupdatedAt\x12C\n" +
	"\x05lists\x18\x03 \x03(\v2-.muxcore.playback.plex.v1.PlexSyncListMessageR\x05lists\"\x15\n" +
	"\x13ListSessionsRequest\"\x9e\x02\n" +
	"\x12PlexSessionMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12)\n" +
	"\x10position_seconds\x18\x06 \x01(\x03R\x0fpositionSeconds\x12)\n" +
	"\x10duration_seconds\x18\a \x01(\x03R\x0fdurationSeconds\x12\x16\n" +
	"\x06paused\x18\b \x01(\bR\x06paused\x12\x16\n" +
	"\x06device\x18\t \x01(\tR\x06device\"`\n" +
	"\x14ListSessionsResponse\x12H\n" +
	"\bsessions\x18\x01 \x03(\v2,.muxcore.playback.plex.v1.PlexSessionMessageR\bsessions\"/\n" +
	"\x0ePlayURLRequest\x12\x1d\n" +
	"\n" +
	"rating_key\x18\x01 \x01(\tR\tratingKey\"#\n" +
	"\x0fPlayURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\xac\x04\n" +
	"\x11PlexBridgeService\x12[\n" +
	"\x06Status\x12'.muxcore.playback.plex.v1.StatusRequest\x1a(.muxcore.playback.plex.v1.StatusResponse\x12y\n" +
	"\x10TerminateSession\x121.muxcore.playback.plex.v1.TerminateSessionRequest\x1a2.muxcore.playback.plex.v1.TerminateSessionResponse\x12p\n" +
	"\rListSyncLists\x12..muxcore.playback.plex.v1.ListSyncListsRequest\x1a/.muxcore.playback.plex.v1.ListSyncListsResponse\x12m\n" +
	"\fListSessions\x12-.muxcore.playback.plex.v1.ListSessionsRequest\x1a..muxcore.playback.plex.v1.ListSessionsResponse\x12^\n" +
	"\aPlayURL\x12(.muxcore.playback.plex.v1.PlayURLRequest\x1a).muxcore.playback.plex.v1.PlayURLResponseB3Z1github.com/Muxcore-Media/plex/proto/plexv1;plexv1b\x06proto3"

var (
	file_proto_plexv1_plex_proto_rawDescOnce sync.Once
	file_proto_plexv1_plex_proto_rawDescData []byte
)

func file_proto_plexv1_plex_proto_rawDescGZIP() []byte {
	file_proto_plexv1_plex_proto_rawDescOnce.Do(func() {
		file_proto_plexv1_plex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plexv1_plex_proto_rawDesc), len(file_proto_plexv1_plex_proto_rawDesc)))
	})
	return file_proto_plexv1_plex_proto_rawDescData
}

var file_proto_plexv1_plex_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_plexv1_plex_proto_goTypes = []any{
	(*StatusRequest)(nil),            // 0: muxcore.playback.plex.v1.StatusRequest
	(*StatusResponse)(nil),           // 1: muxcore.playback.plex.v1.StatusResponse
	(*TerminateSessionRequest)(nil),  // 2: muxcore.playback.plex.v1.TerminateSessionRequest
	(*TerminateSessionResponse)(nil), // 3: muxcore.playback.plex.v1.TerminateSessionResponse
	(*ListSyncListsRequest)(nil),     // 4: muxcore.playback.plex.v1.ListSyncListsRequest
	(*PlexSyncItemMessage)(nil),      // 5: muxcore.playback.plex.v1.PlexSyncItemMessage
	(*PlexSyncListMessage)(nil),      // 6: muxcore.playback.plex.v1.PlexSyncListMessage
	(*ListSyncListsResponse)(nil),    // 7: muxcore.playback.plex.v1.ListSyncListsResponse
	(*ListSessionsRequest)(nil),      // 8: muxcore.playback.plex.v1.ListSessionsRequest
	(*PlexSessionMessage)(nil),       // 9: muxcore.playback.plex.v1.PlexSessionMessage
	(*ListSessionsResponse)(nil),     // 10: muxcore.playback.plex.v1.ListSessionsResponse
	(*PlayURLRequest)(nil),           // 11: muxcore.playback.plex.v1.PlayURLRequest
	(*PlayURLResponse)(nil),          // 12: muxcore.playback.plex.v1.PlayURLResponse
}
var file_proto_plexv1_plex_proto_depIdxs = []int32{
	5,  // 0: muxcore.playback.plex.v1.PlexSyncListMessage.items:type_name -> muxcore.playback.plex.v1.PlexSyncItemMessage
	6,  // 1: muxcore.playback.plex.v1.ListSyncListsResponse.lists:type_name -> muxcore.playback.plex.v1.PlexSyncListMessage
	9,  // 2: muxcore.playback.plex.v1.ListSessionsResponse.sessions:type_name -> muxcore.playback.plex.v1.PlexSessionMessage
	0,  // 3: muxcore.playback.plex.v1.PlexBridgeService.Status:input_type -> muxcore.playback.plex.v1.StatusRequest
	2,  // 4: muxcore.playback.plex.v1.PlexBridgeService.TerminateSession:input_type -> muxcore.playback.plex.v1.TerminateSessionRequest
	4,  // 5: muxcore.playback.plex.v1.PlexBridgeService.ListSyncLists:input_type -> muxcore.playback.plex.v1.ListSyncListsRequest
	8,  // 6: muxcore.playback.plex.v1.PlexBridgeService.ListSessions:input_type -> muxcore.playback.plex.v1.ListSessionsRequest
	11, // 7: muxcore.playback.plex.v1.PlexBridgeService.PlayURL:input_type -> muxcore.playback.plex.v1.PlayURLRequest
	1,  // 8: muxcore.playback.plex.v1.PlexBridgeService.Status:output_type -> muxcore.playback.plex.v1.StatusResponse
	3,  // 9: muxcore.playback.plex.v1.PlexBridgeService.TerminateSession:output_type -> muxcore.playback.plex.v1.TerminateSessionResponse
	7,  // 10: muxcore.playback.plex.v1.PlexBridgeService.ListSyncLists:output_type -> muxcore.playback.plex.v1.ListSyncListsResponse
	10, // 11: muxcore.playback.plex.v1.PlexBridgeService.ListSessions:output_type -> muxcore.playback.plex.v1.ListSessionsResponse
	12, // 12: muxcore.playback.plex.v1.PlexBridgeService.PlayURL:output_type -> muxcore.playback.plex.v1.PlayURLResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_plexv1_plex_proto_init() }
func file_proto_plexv1_plex_proto_init() {
	if File_proto_plexv1_plex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plexv1_plex_proto_rawDesc), len(file_proto_plexv1_plex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plexv1_plex_proto_goTypes,
		DependencyIndexes: file_proto_plexv1_plex_proto_depIdxs,
		MessageInfos:      file_proto_plexv1_plex_proto_msgTypes,
	}.Build()
	File_proto_plexv1_plex_proto = out.File
	file_proto_plexv1_plex_proto_goTypes = nil
	file_proto_plexv1_plex_proto_depIdxs = nil
}
